import './globals.css';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from "@/components/navbar/Navbar"
import { ContextProvider } from "@/context/DarkMode";
import { SearchContextProvider } from '@/context/SearchContext';
import AuthProvider from "@/components/AuthProvider/AuthProvider";
import Footer from "@/components/footer/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Nextflix',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <html lang="en">
    <body className={inter.className}>
      <ContextProvider>
        <SearchContextProvider>
            <AuthProvider>
              <div className='container'>
                <Navbar />
                  {children}
                <Footer />
              </div>
            </AuthProvider>
        </SearchContextProvider>
      </ContextProvider>
    </body> 
  </html>
  )
}
